#!/bin/bash
##
# Shell wrapper to start lfccp.py  
#

## 
# Settings 

CMD=lfccp.py 
#VLET_INSTALL=@VLET_INSTALL@
#VLET_SYSCONFDIR=@VLET_SYSCONFDIR@

# bootstrap startup directory:
if [ -n  "$VLET_INSTALL" ] ; then 
    BASE_DIR="${VLET_INSTALL}"
else
   # Check basedir of installation. Assume script is started from $VLET_INSTALL/bin
   DIRNAME=`dirname $0`
   BASE_DIR=`cd "${DIRNAME}/.." ; pwd`
fi

# default sysconfdir, use BASE_DIR/etc 
if [ -z "${VLET_SYSCONFDIR}" ] ; then 
    VLET_SYSCONFDIR="${BASE_DIR}/etc" 
fi

# source installation settings: 
if [ -f "${VLET_SYSCONFDIR}/vletenv.sh" ] ; then 
   source ${VLET_SYSCONFDIR}/vletenv.sh 
else
   echo "*** Error: couldn't find vletenv.sh (Misconfigured VLET installation ?)."
   exit 1; 
fi

# command: 
"${VLET_INSTALL}/bin/jython.sh" "${VLET_INSTALL}/py/$CMD" $@ 

# keep return value: 
RETVAL=$? 

#return exit code from URIStat
exit $RETVAL; 

